---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geminiex-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geminiex
        component: web
        layer: application
      name: geminiex-web
      namespace: default
    spec:
      containers:
      - env:
        - name: MIX_ENV
          value: prod
        envFrom:
        - configMapRef:
            name: geminiex-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/geminiex:staging
        imagePullPolicy: Always
        name: geminiex-web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geminiex
    component: web
    layer: application
  name: geminiex-web
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: geminiex
    component: web
    layer: application
  sessionAffinity: None
  type: LoadBalancer
